Repository Re-4aliens/backend, pull requests merged in 2024-05, with the labels that each got.

#88 Docs/#87 매칭 restdocs 수정
  src/docs/asciidoc/matching.adoc
  src/test/java/com/aliens/backend/docs/MatchingRestDocsTest.java
Labels: docs

#90 Feat/#36 채팅 도메인 리펙토링, 테스트 커버리지 향상
  src/docs/asciidoc/block.adoc
  src/docs/asciidoc/chat.adoc
  src/docs/asciidoc/report.adoc
  src/main/java/com/aliens/backend/chat/domain/Message.java
  src/main/java/com/aliens/backend/chat/service/ChatAuthValidator.java
  src/main/java/com/aliens/backend/chat/service/ChatService.java
  src/main/java/com/aliens/backend/global/config/interceptor/ChatChannelInterceptor.java
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/chat/domain/ChatParticipantTest.java
  src/test/java/com/aliens/backend/chat/domain/ChatRoomTest.java
  src/test/java/com/aliens/backend/chat/domain/MessageTest.java
  src/test/java/com/aliens/backend/chat/domain/MessageTypeTest.java
  src/test/java/com/aliens/backend/chatting/socket/ChatClient.java
  src/test/java/com/aliens/backend/chatting/socket/WebSocketTest.java
  src/test/java/com/aliens/backend/docs/BlockRestDocsTest.java
  src/test/java/com/aliens/backend/docs/ChatRestDocsTest.java
  src/test/java/com/aliens/backend/docs/ReportRestDocsTest.java
  src/test/java/com/aliens/backend/event/EventPublisherTest.java
  src/test/java/com/aliens/backend/global/BaseIntegrationTest.java
  src/test/resources/application-test.yml
Labels: docs, feat, test

#92 Refactor/#91 INSERT 쿼리 전, SELECT 쿼리가 나가는 문제
  src/main/java/com/aliens/backend/global/response/error/MatchingError.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingApplication.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingResult.java
  src/main/java/com/aliens/backend/mathcing/service/MatchingApplicationService.java
  src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
Labels: feat, refactoring

#101 이메일 전송 오류 해결
  README.md
  build.gradle
  src/docs/asciidoc/email.adoc
  src/main/java/com/aliens/backend/email/controller/EmailController.java
  src/main/java/com/aliens/backend/email/service/EmailContent.java
  src/main/java/com/aliens/backend/email/service/EmailContentType.java
  src/main/java/com/aliens/backend/email/service/EmailService.java
  src/main/java/com/aliens/backend/global/config/WebConfig.java
  src/main/java/com/aliens/backend/global/response/error/EmailError.java
  src/main/resources/static/public/images/character.png
  src/main/resources/templates/emailVerificationComplete.html
  src/test/java/com/aliens/backend/docs/EmailRestDocsTest.java
Labels: fix

#105 Refactor/#103 이미지 파일을 받을 시 같이 받던 DTO를 RequestBody에서 requestpart로 수정
  src/docs/asciidoc/board.adoc
  src/docs/asciidoc/email.adoc
  src/docs/asciidoc/market-boar.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/aliens/backend/board/controller/BoardController.java
  src/main/java/com/aliens/backend/board/controller/MarketController.java
  src/main/java/com/aliens/backend/board/service/CommentService.java
  src/main/java/com/aliens/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aliens/backend/member/controller/MemberController.java
  src/test/java/com/aliens/backend/docs/BoardRestDocsTest.java
  src/test/java/com/aliens/backend/docs/MarketBoardRestDocsTest.java
  src/test/java/com/aliens/backend/docs/MemberRestDocsTest.java
Labels: refactoring

#113 엔티티와 요구사항 변경에 의한 코드 수정
  src/docs/asciidoc/board.adoc
  src/docs/asciidoc/great.adoc
  src/docs/asciidoc/market-boar.adoc
  src/docs/asciidoc/matching.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/notification.adoc
  src/docs/asciidoc/report.adoc
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/auth/domain/Token.java
  src/main/java/com/aliens/backend/auth/domain/repository/TokenRepository.java
  src/main/java/com/aliens/backend/auth/service/AuthService.java
  src/main/java/com/aliens/backend/block/domain/Block.java
  src/main/java/com/aliens/backend/board/controller/BoardController.java
  src/main/java/com/aliens/backend/board/controller/ReportController.java
  src/main/java/com/aliens/backend/board/domain/Board.java
  src/main/java/com/aliens/backend/board/domain/BoardImage.java
  src/main/java/com/aliens/backend/board/domain/BoardReport.java
  src/main/java/com/aliens/backend/board/domain/Comment.java
  src/main/java/com/aliens/backend/board/domain/Great.java
  src/main/java/com/aliens/backend/board/domain/MarketInfo.java
  src/main/java/com/aliens/backend/chat/domain/ChatParticipant.java
  src/main/java/com/aliens/backend/chat/domain/ChatReport.java
  src/main/java/com/aliens/backend/chat/domain/ChatRoom.java
  src/main/java/com/aliens/backend/chat/domain/repository/ChatParticipantRepository.java
  src/main/java/com/aliens/backend/email/domain/EmailAuthentication.java
  src/main/java/com/aliens/backend/global/response/success/NotificationSuccess.java
  src/main/java/com/aliens/backend/mathcing/controller/dto/response/MatchingResultResponse.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingResult.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingRound.java
  src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
  src/main/java/com/aliens/backend/member/domain/MemberImage.java
  src/main/java/com/aliens/backend/member/domain/MemberInfo.java
  src/main/java/com/aliens/backend/member/sevice/MemberInfoService.java
  src/main/java/com/aliens/backend/member/sevice/SymmetricKeyEncoder.java
  src/main/java/com/aliens/backend/notification/controller/NotificationController.java
  src/main/java/com/aliens/backend/notification/domain/FcmToken.java
  src/main/java/com/aliens/backend/notification/domain/Notification.java
  src/main/java/com/aliens/backend/notification/domain/repository/NotificationRepository.java
  src/main/java/com/aliens/backend/notification/service/NotificationService.java
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/docs/BoardRestDocsTest.java
  src/test/java/com/aliens/backend/docs/MarketBoardRestDocsTest.java
  src/test/java/com/aliens/backend/docs/MatchingRestDocsTest.java
  src/test/java/com/aliens/backend/docs/NotificationRestDocsTest.java
  src/test/java/com/aliens/backend/encode/SymmetricKeyEncoderTest.java
  src/test/java/com/aliens/backend/global/DatabaseCleanup.java
  src/test/java/com/aliens/backend/global/DummyGenerator.java
  src/test/java/com/aliens/backend/member/service/MemberInfoServiceTest.java
Labels: refactoring
