Repository Re-4aliens/backend, pull requests merged in 2024-06, with the labels that each got.

#119 Fix/#118 매칭을 신청했으나, 매칭되지 않은 사용자의 매칭 상태 변경기능 추가
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/global/response/error/MatchingError.java
  src/main/java/com/aliens/backend/mathcing/business/model/Participant.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingApplication.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingResult.java
  src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingApplicationRepository.java
  src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingRoundRepository.java
  src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
  src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
Labels: feat, fix, style, test

#116 Feat/#115 채팅 알림 기능 구현
  README.md
  src/main/java/com/aliens/backend/chat/service/ChatService.java
  src/main/java/com/aliens/backend/global/response/error/NotificationError.java
  src/main/java/com/aliens/backend/notification/domain/FcmTokenRepository.java
  src/test/java/com/aliens/backend/chatting/service/ChatServiceTest.java
Labels: feat

#120 2024-06-10 [Release Not]
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/chat/service/ChatService.java
  src/main/java/com/aliens/backend/global/response/error/MatchingError.java
  src/main/java/com/aliens/backend/global/response/error/NotificationError.java
  src/main/java/com/aliens/backend/mathcing/business/model/Participant.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingApplication.java
  src/main/java/com/aliens/backend/mathcing/domain/MatchingResult.java
  src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingApplicationRepository.java
  src/main/java/com/aliens/backend/mathcing/domain/repository/MatchingRoundRepository.java
  src/main/java/com/aliens/backend/mathcing/service/MatchingProcessService.java
  src/main/java/com/aliens/backend/notification/domain/FcmTokenRepository.java
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/chatting/service/ChatServiceTest.java
  src/test/java/com/aliens/backend/matching/unit/service/MatchingApplicationServiceTest.java
Labels: release

#121 Chore/#117 배포 설정 변경(Docker)
  .github/workflows/friendship-pipeline.yml
Labels: chore

#130 created date 수정, 파일 확장자 추가, 불필요한 쿼리 수정
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/board/controller/BoardController.java
  src/main/java/com/aliens/backend/board/domain/Board.java
  src/main/java/com/aliens/backend/board/domain/Comment.java
  src/main/java/com/aliens/backend/chat/service/ChatService.java
  src/main/java/com/aliens/backend/member/domain/MemberImage.java
  src/main/java/com/aliens/backend/member/domain/MemberInfo.java
  src/main/java/com/aliens/backend/member/sevice/MemberInfoService.java
  src/main/java/com/aliens/backend/notification/domain/FcmTokenRepository.java
  src/main/java/com/aliens/backend/notification/domain/Notification.java
  src/main/java/com/aliens/backend/notification/service/NotificationService.java
  src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/docs/BoardRestDocsTest.java
  src/test/java/com/aliens/backend/global/DummyGenerator.java
Labels: fix, refactoring
