Repository Re-4aliens/backend, pull requests merged in 2024-01, with the labels that each got.

#3 Feat/#1 rest docs 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/aliens/backend/auth/controller/AuthController.java
  src/main/java/com/aliens/backend/auth/controller/dto/AuthToken.java
  src/main/java/com/aliens/backend/auth/controller/dto/LoginRequest.java
  src/main/java/com/aliens/backend/auth/service/AuthService.java
  src/test/java/com/aliens/backend/docs/AuthDocTest.java
Labels: chore, docs

#4 Chore/#2 Dockerfile 구성 추가
  Dockerfile
Labels: chore

#5 2024-01-16 [Release Note]
  Dockerfile
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/aliens/backend/auth/controller/AuthController.java
  src/main/java/com/aliens/backend/auth/controller/dto/AuthToken.java
  src/main/java/com/aliens/backend/auth/controller/dto/LoginRequest.java
  src/main/java/com/aliens/backend/auth/service/AuthService.java
  src/test/java/com/aliens/backend/docs/AuthDocTest.java
Labels: release

#7 Feat/#6 Authentication 구현 및 기본 설정
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/aliens/backend/auth/controller/AuthController.java
  src/main/java/com/aliens/backend/auth/controller/dto/LoginMember.java
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/auth/domain/MemberRole.java
  src/main/java/com/aliens/backend/auth/domain/Token.java
  src/main/java/com/aliens/backend/auth/domain/repository/MemberRepository.java
  src/main/java/com/aliens/backend/auth/domain/repository/TokenRepository.java
  src/main/java/com/aliens/backend/auth/service/AuthService.java
  src/main/java/com/aliens/backend/auth/service/PasswordEncoder.java
  src/main/java/com/aliens/backend/auth/service/TokenProvider.java
  src/main/java/com/aliens/backend/global/config/WebConfig.java
  src/main/java/com/aliens/backend/global/config/resolver/Login.java
  src/main/java/com/aliens/backend/global/config/resolver/TokenInfoResolver.java
  src/main/java/com/aliens/backend/global/error/CommonError.java
  src/main/java/com/aliens/backend/global/error/ErrorCode.java
  src/main/java/com/aliens/backend/global/error/MemberError.java
  src/main/java/com/aliens/backend/global/error/TokenError.java
  src/main/java/com/aliens/backend/global/exception/ApiExceptionHandler.java
  src/main/java/com/aliens/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aliens/backend/global/exception/RestApiException.java
  src/main/java/com/aliens/backend/global/property/EncodeProperties.java
  src/main/java/com/aliens/backend/global/property/JWTProperties.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/auth/service/AuthServiceTest.java
  src/test/java/com/aliens/backend/auth/service/TokenProviderTest.java
  src/test/java/com/aliens/backend/docs/AuthDocTest.java
Labels: chore, docs, feat, test

#21 Revert "Feat/#14 대칭키 암호화, 복호화 기능 구현"
  src/main/java/com/aliens/backend/encode/EncoderProperties.java
  src/main/java/com/aliens/backend/encode/SymmetricKeyEncoder.java
  src/test/java/com/aliens/backend/encode/SymmetricKeyEncoderTest.java
Labels: fix

#22 Revert 21 revert 19 feat/#14 encod
  src/main/java/com/aliens/backend/encode/EncoderProperties.java
  src/main/java/com/aliens/backend/encode/SymmetricKeyEncoder.java
  src/test/java/com/aliens/backend/encode/SymmetricKeyEncoderTest.java
Labels: fix

#18 Feat/#12 image uploader 구현
  build.gradle
  src/main/java/com/aliens/backend/uploader/AWSConfig.java
  src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
  src/main/java/com/aliens/backend/uploader/S3File.java
  src/main/java/com/aliens/backend/uploader/S3UploadProperties.java
  src/main/java/com/aliens/backend/uploader/UploadFileRequest.java
  src/test/java/com/aliens/backend/uploader/AwsS3MockConfig.java
  src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
Labels: chore, feat, test

#11 Chore/#9 배포 자동화 파이프라인 friendship-pipeline.yml 수정
  .github/workflows/friendship-pipeline.yml
Labels: chore, fix

#10 Chore/#8 Asciidoctor 오류(asGemPath())로 인해 build.gradle 수정
  build.gradle
  gradlew
Labels: chore, fix

#23 Feat/#13 email authentication 기능 구현
  build.gradle
  src/docs/asciidoc/authentication.adoc
  src/docs/asciidoc/email.adoc
  src/main/java/com/aliens/backend/auth/service/PasswordEncoder.java
  src/main/java/com/aliens/backend/email/controller/EmailController.java
  src/main/java/com/aliens/backend/email/controller/response/EmailResponse.java
  src/main/java/com/aliens/backend/email/domain/EmailAuthentication.java
  src/main/java/com/aliens/backend/email/domain/repository/EmailAuthenticationRepository.java
  src/main/java/com/aliens/backend/email/service/EmailContent.java
  src/main/java/com/aliens/backend/email/service/EmailSender.java
  src/main/java/com/aliens/backend/email/service/EmailService.java
  src/main/java/com/aliens/backend/global/config/MailConfig.java
  src/main/java/com/aliens/backend/global/encode/SymmetricKeyEncoder.java
  src/main/java/com/aliens/backend/global/error/EmailError.java
  src/main/java/com/aliens/backend/global/property/EmailProperties.java
  src/main/java/com/aliens/backend/global/property/PasswordEncodeProperties.java
  src/main/java/com/aliens/backend/global/property/SymmetricEncoderProperties.java
  src/test/java/com/aliens/backend/docs/EmailDocTest.java
  src/test/java/com/aliens/backend/email/sender/EmailContentTest.java
  src/test/java/com/aliens/backend/email/sender/EmailSenderTest.java
  src/test/java/com/aliens/backend/email/service/EmailServiceTest.java
  src/test/java/com/aliens/backend/encode/SymmetricKeyEncoderTest.java
Labels: chore, feat, test

#27 2024-01-28 [Release Note]
  .github/workflows/friendship-pipeline.yml
  .gitignore
  build.gradle
  gradlew
  src/docs/asciidoc/authentication.adoc
  src/docs/asciidoc/email.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/aliens/backend/auth/controller/AuthController.java
  src/main/java/com/aliens/backend/auth/controller/dto/LoginMember.java
  src/main/java/com/aliens/backend/auth/domain/Member.java
  src/main/java/com/aliens/backend/auth/domain/MemberRole.java
  src/main/java/com/aliens/backend/auth/domain/Token.java
  src/main/java/com/aliens/backend/auth/domain/repository/MemberRepository.java
  src/main/java/com/aliens/backend/auth/domain/repository/TokenRepository.java
  src/main/java/com/aliens/backend/auth/service/AuthService.java
  src/main/java/com/aliens/backend/auth/service/PasswordEncoder.java
  src/main/java/com/aliens/backend/auth/service/TokenProvider.java
  src/main/java/com/aliens/backend/email/controller/EmailController.java
  src/main/java/com/aliens/backend/email/controller/response/EmailResponse.java
  src/main/java/com/aliens/backend/email/domain/EmailAuthentication.java
  src/main/java/com/aliens/backend/email/domain/repository/EmailAuthenticationRepository.java
  src/main/java/com/aliens/backend/email/service/EmailContent.java
  src/main/java/com/aliens/backend/email/service/EmailSender.java
  src/main/java/com/aliens/backend/email/service/EmailService.java
  src/main/java/com/aliens/backend/global/config/MailConfig.java
  src/main/java/com/aliens/backend/global/config/WebConfig.java
  src/main/java/com/aliens/backend/global/config/resolver/Login.java
  src/main/java/com/aliens/backend/global/config/resolver/TokenInfoResolver.java
  src/main/java/com/aliens/backend/global/encode/SymmetricKeyEncoder.java
  src/main/java/com/aliens/backend/global/error/CommonError.java
  src/main/java/com/aliens/backend/global/error/EmailError.java
  src/main/java/com/aliens/backend/global/error/ErrorCode.java
  src/main/java/com/aliens/backend/global/error/MemberError.java
  src/main/java/com/aliens/backend/global/error/TokenError.java
  src/main/java/com/aliens/backend/global/exception/ApiExceptionHandler.java
  src/main/java/com/aliens/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aliens/backend/global/exception/RestApiException.java
  src/main/java/com/aliens/backend/global/property/EmailProperties.java
  src/main/java/com/aliens/backend/global/property/JWTProperties.java
  src/main/java/com/aliens/backend/global/property/PasswordEncodeProperties.java
  src/main/java/com/aliens/backend/global/property/SymmetricEncoderProperties.java
  src/main/java/com/aliens/backend/uploader/AWSConfig.java
  src/main/java/com/aliens/backend/uploader/AwsS3Uploader.java
  src/main/java/com/aliens/backend/uploader/S3File.java
  src/main/java/com/aliens/backend/uploader/S3UploadProperties.java
  src/main/java/com/aliens/backend/uploader/UploadFileRequest.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/aliens/backend/auth/service/AuthServiceTest.java
  src/test/java/com/aliens/backend/auth/service/TokenProviderTest.java
  src/test/java/com/aliens/backend/docs/AuthDocTest.java
  src/test/java/com/aliens/backend/docs/EmailDocTest.java
  src/test/java/com/aliens/backend/email/sender/EmailContentTest.java
  src/test/java/com/aliens/backend/email/sender/EmailSenderTest.java
  src/test/java/com/aliens/backend/email/service/EmailServiceTest.java
  src/test/java/com/aliens/backend/encode/SymmetricKeyEncoderTest.java
  src/test/java/com/aliens/backend/uploader/AwsS3MockConfig.java
  src/test/java/com/aliens/backend/uploader/AwsS3UploaderTest.java
Labels: release
