Repository Re-4aliens/backend, pull requests merged in 2024-10, with the labels that each got.

#176 fix/#175 내가 쓴 게시글, 내가 댓글 쓴 게시글 쿼리 수정
  src/main/java/com/aliens/backend/board/domain/repository/custom/BoardCustomRepositoryImpl.java
  src/test/java/com/aliens/backend/board/service/BoardServiceReadTest.java
Labels: fix

#187 fix(FcmSender) : sendMatchedNotification의 알림 전송 방식을 multi -> single 로 변경
  src/main/java/com/aliens/backend/mathcing/service/MatchingRoundService.java
  src/main/java/com/aliens/backend/notification/service/FcmSender.java
  src/test/java/com/aliens/backend/global/BaseIntegrationTest.java
  src/test/java/com/aliens/backend/matching/unit/service/MatchingRoundServiceTest.java
Labels: feat, fix

#191 Fix/#189 fcm전송 방식 변경
  src/main/java/com/aliens/backend/board/service/CommentEventPublisher.java
  src/main/java/com/aliens/backend/board/service/CommentService.java
  src/main/java/com/aliens/backend/board/service/GreatService.java
  src/main/java/com/aliens/backend/member/controller/dto/response/MemberResponse.java
  src/main/java/com/aliens/backend/member/sevice/MemberInfoService.java
  src/main/java/com/aliens/backend/notification/controller/dto/NotificationRequest.java
  src/main/java/com/aliens/backend/notification/service/FcmSender.java
  src/main/java/com/aliens/backend/notification/service/NotificationService.java
  src/test/java/com/aliens/backend/docs/MemberRestDocsTest.java
  src/test/java/com/aliens/backend/global/BaseIntegrationTest.java
  src/test/java/com/aliens/backend/global/DummyGenerator.java
  src/test/java/com/aliens/backend/notification/NotificationServiceTest.java
Labels: fix

#192 2024-10-18 [Release Note]
  src/main/java/com/aliens/backend/board/service/CommentService.java
  src/main/java/com/aliens/backend/board/service/GreatService.java
  src/main/java/com/aliens/backend/notification/controller/dto/NotificationRequest.java
  src/main/java/com/aliens/backend/notification/service/FcmSender.java
  src/main/java/com/aliens/backend/notification/service/NotificationService.java
  src/test/java/com/aliens/backend/docs/MemberRestDocsTest.java
  src/test/java/com/aliens/backend/global/BaseIntegrationTest.java
  src/test/java/com/aliens/backend/global/DummyGenerator.java
  src/test/java/com/aliens/backend/notification/NotificationServiceTest.java
Labels: release

#195 Fix/#194 FcmSender에 비동기 기능 추가
  src/main/java/com/aliens/backend/global/config/AsyncConfig.java
  src/main/java/com/aliens/backend/notification/service/FcmSender.java
Labels: fix, refactoring

#197 Feat/#196 elk stack
  .github/workflows/friendship-pipeline.yml
  .gitignore
  Dockerfile
  src/main/resources/log/config/error-config.xml
  src/main/resources/log/config/info-config.xml
  src/main/resources/log/config/warn-config.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
  src/main/resources/logback-spring.xml
Labels: chore, feat

#204 문의하기 기능 개발
  src/main/java/com/aliens/backend/global/response/success/InquirySuccess.java
  src/main/java/com/aliens/backend/inquire/InquiryController.java
  src/main/java/com/aliens/backend/inquire/controller/request/InquiryCreateRequest.java
  src/main/java/com/aliens/backend/inquire/domain/Inquiry.java
  src/main/java/com/aliens/backend/inquire/repository/InquiryRepository.java
  src/main/java/com/aliens/backend/inquire/service/InquiryService.java
  src/test/java/com/aliens/backend/docs/BaseRestDocsTest.java
  src/test/java/com/aliens/backend/docs/InquiryRestDocsTest.java
  src/test/java/com/aliens/backend/inquire/service/InquiryServiceTest.java
Labels: feat

#208 2024-10-24 [Release Note]
  src/main/java/com/aliens/backend/notification/service/FcmSender.java
Labels: release
